name: flutter_guidelines
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  #code generator for unions/pattern-matching/copy.
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  #router
  auto_route: ^3.2.2

  #state management
  provider: ^6.0.2  
  flutter_bloc: ^8.0.1

  #The Flutter code generator for your assets, fonts, colors
  flutter_gen: ^4.1.5

  #Simplify form representation and validation in a generic way
  formz: ^0.4.1

  #validators
  email_validator: ^2.0.1

  #A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData, 
  #Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.4

  #easy and fast internationalization
  easy_localization: ^3.0.0

  #bottom navigation bar, but with a few key promises
  salomon_bottom_bar: ^3.2.0

  #
  page_transition: ^2.0.5
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7 
  injectable_generator: ^1.5.3
  flutter_gen_runner: ^4.1.5
  auto_route_generator: ^3.2.1
  freezed: ^1.1.1
  json_serializable: ^6.1.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_gen:
  output: lib/gen/  # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/langs/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
